### ISSUE TITLE
About parameter "quantile"

### ISSUE THREAD

**Issue by cjyGeo** [gisgyf/OMGD#1]
Hello,

I have thoroughly read the documentation you provided on GitHub, but I still don't fully understand the parameter "quantile". I would appreciate a more straightforward explanation.

Sincere regards.

**Comment by gisgyf** [comment]
***Subject: Explanation of the "quantile" Parameter***

Thank you for your question about the "quantile" parameter.

The quantile setting determines how many explanatory variables or variable combinations are included in calculating the average Q value. Here’s a breakdown:

When we calculate the Q values for each explanatory variable or combination, we might obtain five Q values, ranging from 0.1 to 0.5 in increments of 0.1. Imagine we sort these Q values in ascending order. If the quantile is set to 0, it references the lowest Q value (0.1). In this case, any Q value greater than or equal to 0.1 (all the Q values) will be used to calculate the average Q value. Each spatial scale will have a different "average" Q value, which helps in identifying the optimal spatial scale.

Similarly, if the quantile is set to 0.8 (80%), it refers to the fourth Q value (0.4) after sorting. So, any Q value greater than or equal to 0.4 will be included in the average Q calculation.

Using **quantile** in the scale detector allows us to focus on a subset of explanatory variables or combinations that most effectively explain the distribution of the dependent variable, instead of considering all of them when searching for the optimal spatial scale.

I hope this clarifies your question. Please feel free to reach out if you need further clarification.

P.S. I’d be grateful if you’d consider recommending this article and code to others who may find it useful.

Sincere regards, 
Yingfeng Guo

**Comment by cjyGeo** [comment]
Of course, I would be happy to recommend your article and code to others, Mr. Guo. I have a WeChat public account and will share your article and GitHub link with my followers.

I believe I understand your point: if I have 7 Q-values, such as 0.1, 0.3, 0.2, 0.6, 0.9, 0.4, and 0.97, I would first sort them in ascending order, which gives 0.1, 0.2, 0.3, 0.4, 0.6, 0.9, and 0.97. When I set the quantile to 0.5, any Q-value greater than or equal to 0.4 will be used to calculate the average Q-value.

Thanks for your detailed response.

**Comment by cjyGeo** [comment]
After reviewing the test.ipynb file with your explanation in mind, I believe my understanding is correct.

**Comment by gisgyf** [comment]
> Of course, I would be happy to recommend your article and code to others, Mr. Guo. I have a WeChat public account and will share your article and GitHub link with my followers.
> 
> I believe I understand your point: if I have 7 Q-values, such as 0.1, 0.3, 0.2, 0.6, 0.9, 0.4, and 0.97, I would first sort them in ascending order, which gives 0.1, 0.2, 0.3, 0.4, 0.6, 0.9, and 0.97. When I set the quantile to 0.5, any Q-value greater than or equal to 0.4 will be used to calculate the average Q-value.
> 
> Thanks for your detailed response.

That's correct and I really appreciate your recommendation, have a nice day~

**Comment by pzzmk** [comment]
您好！关于变量分层是否可以使用OPGD先计算出X的层数，再将层数作为OMGD的输入参数？

**Comment by gisgyf** [comment]
> 您好！关于变量分层是否可以使用OPGD先计算出X的层数，再将层数作为OMGD的输入参数？

为什么需要先用OPGD计算出X的层数，再将层数作为OMGD的输入参数呢？

**Comment by pzzmk** [comment]
不好意思，我仔细看了下文章，理解错了
